### ISSUE TITLE
Interop with elm-markup

### ISSUE THREAD

**Issue by ebrightfield** [mdgriffith/elm-ui#176] opened 2020-01-14 20:35 UTC
Apologies if this isn't the appropriate place to post this. I was unable to get an answer on Elm Slack, and I've found similar "issues"(scare quotes because I'm probably just incorrectly using the libraries) on here. 

If one were to try to carbon-copy the Blog example from the elm-markup repo, but using elm-ui components instead of Html, is there a straightforward way to recreate links as a `Mark.annotation` in a `Mark.textWith` without introducing undesired line breaks between text elements? I have so far tried implementing the rendering with `Element.row`, `Element.wrappedRows` and `Element.paragraph`. 

https://ellie-app.com/7LJ9rf4NXrHa1

Putting this issue here rather than the elm-markup repo because I think the issue is on the side of elm-ui. At the very least, it's got to be an issue with how I'm interfacing between the two libraries. I've tried isolating the issue by removing all the elm-markup code, but the task proved a bit too complex for me to handle.

**Comment by Y0hy0h** [comment] 2020-01-30 11:21
I played around with your Ellie and I'm pretty sure this is a duplicate of #173 which demonstrates the fundamental problem more clearly.

**Comment by mdgriffith** [comment] 2020-05-02 04:18
Thanks for the issue!  Yeah, this is definitely an issue that makes it awkward. 

I'm currently trying to clean up the issues in preparation for some bug fixes, so I'm going to close this and track the issue in #173 .

**Closed by mdgriffith** 2020-05-02 04:18 UTC
